#!/usr/bin/env python3
"""Rebuild R:/K: lines of lib/pref/graf-new.prf for Adam Bolt's 16x16 tiles,
matching TinyAngband monsters/objects by name against ToME's mapping.
Usage: port-tiles.py /path/to/AngbandPlus-ToME/lib"""
import re, sys, os

tome = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))

def norm(s):
    return re.sub(r'[&~]', '', s).replace('  ', ' ').strip().lower()

def info(path, tag):
    """index -> dict(name, glyph, color, tval, sval) from an *_info.txt file."""
    d, cur = {}, None
    for l in open(path, errors='replace'):
        l = l.rstrip('\n')
        if l.startswith('N:'):
            p = l.split(':', 2); cur = int(p[1])
            d[cur] = {'name': norm(p[2])}
        elif cur is None:
            continue
        elif tag and l.startswith(tag):                     # English name in TinyAngband
            d[cur]['name'] = norm(l[2:])
        elif l.startswith('G:'):
            p = l.split(':')
            d[cur]['glyph'], d[cur]['color'] = p[1], p[2] if len(p) > 2 else ''
        elif l.startswith('I:') and 'tval' not in d[cur]:
            p = l.split(':'); d[cur]['tval'], d[cur]['sval'] = p[1], p[2]
    return d

def prf(path, kind):
    return {int(m[1]): m[2] for m in re.finditer(rf'^{kind}:(\d+):(0x\w+/0x\w+)', open(path).read(), re.M)}

def match(ours, theirs, tiles, keys):
    out, stats = {}, [0] * (len(keys) + 1)
    for i, e in ours.items():
        for n, key in enumerate(keys):
            k = key(e)
            hit = next((tiles[j] for j, t in theirs.items() if j in tiles and key(t) == k), None)
            if hit: out[i] = hit; stats[n] += 1; break
        else:
            stats[-1] += 1
    return out, stats

T = os.path.join(here, 'lib')
mons, mstat = match(info(f'{T}/edit/r_info.txt', 'E:'), info(f'{tome}/edit/r_info.txt', None),
                    prf(f'{tome}/pref/graf-new.prf', 'R'),
                    [lambda e: e['name'], lambda e: (e.get('glyph'), e.get('color')), lambda e: e.get('glyph')])
objs, ostat = match(info(f'{T}/edit/k_info.txt', 'E:'), info(f'{tome}/edit/k_info.txt', None),
                    prf(f'{tome}/pref/graf-new.prf', 'K'),
                    [lambda e: (e.get('tval'), e['name']), lambda e: e['name'],
                     lambda e: (e.get('tval'), e.get('sval')), lambda e: (e.get('glyph'), e.get('color'))])
mons[0] = '0x89/0xA0'   # the player: Adam Bolt's human (ToME's R:0 is a mug placeholder;
                         # row 9 cols 0x20+ are the race sprites, see cave.c map_info)
# Flavored rings share tiles at random each game (flavor.c shuffle_flavors),
# so every shuffled ring gets the plain ring tile; ToME's odd ones (warning
# sign, figures, spell effects) could otherwise turn up on any ring.
# 327 (the One Ring) has a fixed flavor and keeps its own tile.
for i in list(range(104, 141)) + list(range(322, 327)):
    objs[i] = '0x84/0x83'
# Statues draw their monster's tile in grey (defines.h statue_pict_p); this is
# only the fallback: the grey stone golem made by grey-statues.py.
for i in range(329, 339):
    objs[i] = '0xD1/0x8B'

src = f'{T}/pref/graf-new.prf'
if not os.path.exists(src + '.orig'):
    os.rename(src, src + '.orig')
keep = [l for l in open(src + '.orig') if not re.match(r'[RK]:', l)]  # S:/F: lines are already right
with open(src, 'w') as f:
    f.writelines(keep)
    f.write('\n##### Monsters / objects, generated by port-tiles.py #####\n\n')
    f.writelines(f'R:{i}:{v}\n' for i, v in sorted(mons.items()))
    f.writelines(f'K:{i}:{v}\n' for i, v in sorted(objs.items()))
print('monsters name/glyph+color/glyph/none:', mstat)
print('objects tval+name/name/tval+sval/glyph+color/none:', ostat)
